=== KnowledgeCaptureAndDiscovery/expect_site/projects/agents/phosphorus/system/capabilities/yolanda.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.0.7 NT (http://www.xmlspy.com) by pablo yanez (isi usc) -->
<!ELEMENT person (Name, UserId, Photo?, projects*, systems*, topics*, position, group?, capabilities)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT UserId (#PCDATA)>
<!ELEMENT Photo (#PCDATA)>
<!ELEMENT projects (#PCDATA)>
<!ELEMENT systems (#PCDATA)>
<!ELEMENT topics (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT capabilities (capability+)>
<!ELEMENT capability (NlDescription, MethodGoal+)>
<!ELEMENT NlDescription (#PCDATA)>
<!ELEMENT MethodGoal (VarGoalForm+)>
<!ELEMENT VarGoalForm (GoalName, ManyVarGoalArgument)>
<!ELEMENT GoalName (#PCDATA)>
<!ELEMENT ManyVarGoalArgument (VarGoalArgument+)>
<!ELEMENT VarGoalArgument (ParameterName, MethodGoalArgument)>
<!ELEMENT ParameterName (#PCDATA)>
<!ELEMENT MethodGoalArgument (VariableName?, t, ComplexData?)>
<!ELEMENT VariableName (#PCDATA)>
<!ELEMENT t (#PCDATA)>
<!ATTLIST t
	name CDATA #REQUIRED
>
<!ELEMENT ComplexData (t, (ConceptName | InstanceName | ComplexData?))>
<!ELEMENT ConceptName (#PCDATA)>
<!ELEMENT InstanceName (#PCDATA)>

=== KnowledgeCaptureAndDiscovery/expect_site/projects/agents/phosphorus/system/capabilities/lizh.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.0.7 NT (http://www.xmlspy.com) by pablo yanez (isi usc) -->
<?xml-stylesheet type="text/xsl" href="lizh.xsl"?>
<!DOCTYPE person SYSTEM "yolanda.dtd">
<person>
	<Name>Liz Hall</Name>
	<UserId>lizh</UserId>
	<Photo>photo/lizh</Photo>
	<projects/>
	<systems/>
	<topics/>
	<position>Project Assistant</position>
	<group>Expect, NL, Ariadne</group>
	<capabilities>
		<capability>
			<NlDescription>Arrange travel for researcher to meeting</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>plan</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<VariableName>?v</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="SPEC-OF"/>
									<ConceptName>travel</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>FOR</ParameterName>
							<MethodGoalArgument>
								<VariableName>?l</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>researcher</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>TO</ParameterName>
							<MethodGoalArgument>
								<VariableName>?M</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>meeting</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Submit reimbursement for traveler</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>submit</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<VariableName>?v</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>reimbursement</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>FOR</ParameterName>
							<MethodGoalArgument>
								<VariableName>?t</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>travelers</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Assist researcher</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>assist</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<VariableName>?v</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>researcher</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Type documents</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>type</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>document</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Edit the InSiDer
</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>write</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>obj</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST"/>
									<InstanceName>InSiDer</InstanceName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
	</capabilities>
</person>

=== KnowledgeCaptureAndDiscovery/expect_site/projects/agents/phosphorus/system/capabilities/tar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.0.7 NT (http://www.xmlspy.com) by pablo yanez (isi usc) -->
<?xml-stylesheet type="text/xsl" href="tar.xsl"?>
<!DOCTYPE person SYSTEM "yolanda.dtd">
<person>
	<Name>Tom russ</Name>
	<UserId>tar</UserId>
	<Photo>photo/russ</Photo>
	<projects>Electric Elves</projects>
	<projects>Loom</projects>
	<projects>RKF</projects>
	<projects>PowerLoom</projects>
	<projects>CoABS</projects>
	<systems>Loom</systems>
	<systems>PowerLoom</systems>
	<systems>Stella</systems>
	<systems>Ontosaurus</systems>
	<systems>InterestMatcher</systems>
	<topics>Knowledge representation
</topics>
	<topics>Medical reasoning
      </topics>
	<topics>Interfaces for KB editing</topics>
	<position>Research ScientISt</position>
	<group>Loom</group>
	<capabilities>
		<capability>
			<NlDescription>Answer questions about Loom</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>answer </GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="SET-OF"/>
									<ComplexData>
										<t name="INST-OF"/>
										<ConceptName>question</ConceptName>
									</ComplexData>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>ABOUT</ParameterName>
							<MethodGoalArgument>
								<t name="IS"/>
								<ComplexData>
									<t name="INST"/>
									<ConceptName>loom</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Give a demo of Ontosaurus to person</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>give </GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<VariableName>?V</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST-OF"/>
									<InstanceName>DEMO</InstanceName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OF</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST"/>
									<ConceptName>Ontosaurus</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>TO</ParameterName>
							<MethodGoalArgument>
								<VariableName>?p</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>person</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Give demo of Interest Matcher</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>give </GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<VariableName>?V</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST"/>
									<ConceptName>demo</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OF</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST"/>
									<ConceptName>InterestMatcher</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>TO</ParameterName>
							<MethodGoalArgument>
								<VariableName>?p</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>person</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Write paper  conference</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>write</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="SPEC-OF"/>
									<ConceptName>technical paper</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>FOR</ParameterName>
							<MethodGoalArgument>
								<VariableName>?p</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>conference</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Give demo of Powerloom</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>give demo</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="SPEC-OF"/>
									<ConceptName>DEMO</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>of</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="INST"/>
									<InstanceName>PowerLoom</InstanceName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Present research results</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>PRESENT</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>obj</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="SET-OF"/>
									<ComplexData>
										<t name="INST-OF"/>
										<ConceptName>Research Result</ConceptName>
									</ComplexData>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Review papers about knowledge representation</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>review</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="SPEC-OF"/>
									<ConceptName>paper</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>ABOUT</ParameterName>
							<MethodGoalArgument>
								<VariableName>?v</VariableName>
								<t name="IS"/>
								<ComplexData>
									<t name="SPEC-OF"/>
									<ConceptName>knowledge representation</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
	</capabilities>
</person>

=== KnowledgeCaptureAndDiscovery/expect_site/projects/agents/phosphorus/system/capabilities/russ.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.0.7 (http://www.xmlspy.com) by pablo yanez (isi usc) -->
<?xml-stylesheet type="text/xsl" href="russ.xsl"?>
<!DOCTYPE person SYSTEM "yolanda.dtd">
<person>
	<Name>Tom russ</Name>
	<UserId>tar</UserId>
	<Photo>photo/russ</Photo>
	<projects>Electric Elves</projects>
	<projects>loom</projects>
	<projects>RKF</projects>
	<projects>PowerLoom</projects>
	<projects>CoABS</projects>
	<systems>loom</systems>
	<systems>PowerLoom</systems>
	<systems>stella</systems>
	<systems>ontosaurus</systems>
	<topics>Knowledge representation
</topics>
	<topics>Medical reasoning
      </topics>
	<topics>Interfaces for KB editting</topics>
	<position>Research Scientist</position>
	<capabilities>
		<capability>
			<NlDescription>answer questions about loom (often by mail)</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>answer </GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<t name="ESPEC-OF"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>Question</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>about</ParameterName>
							<MethodGoalArgument>
								<t name=""/>
								<ComplexData>
									<t name="EXPC-OF"/>
									<ConceptName>loom</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>give a demo of Ontosaurus to anyone</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>give </GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<t name="INST-OF"/>
								<InstanceName>DEMO</InstanceName>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>of</ParameterName>
							<MethodGoalArgument>
								<t name="INST-OF"/>
								<InstanceName>interest matcher</InstanceName>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>give a demo of interest matcher</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>give </GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<t name="EXPC-OF"/>
								<InstanceName>DEMO</InstanceName>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>of</ParameterName>
							<MethodGoalArgument>
								<t name="EXPC-OF"/>
								<InstanceName>interest matcher</InstanceName>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Write technical paper about knowledge representation for journals and conferences</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>write</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>obj</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="is"/>
								<ComplexData>
									<t name="EXPC-OF"/>
									<ConceptName>technical paper</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>of</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="is"/>
								<ComplexData>
									<t name="EXPC-OF"/>
									<ConceptName>knowledge adquisition</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>in</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="is"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>conferences</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>in</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="is"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>journals</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Give demo of Powerloom</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>give demo</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>OBJ</ParameterName>
							<MethodGoalArgument>
								<t name="IS/"/>
								<ComplexData>
									<t name="EXPC-OF"/>
									<ConceptName>DEMO</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>of</ParameterName>
							<MethodGoalArgument>
								<t name="IS"/>
								<ComplexData>
									<t name="EXPC-OF"/>
									<ConceptName>powerloom</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>Present the research results</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>PRESENT</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>obj</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="is"/>
								<ComplexData>
									<t name="INST-OF"/>
									<ConceptName>RESEARCH RESULTS</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
		<capability>
			<NlDescription>review papers about knowledge representation</NlDescription>
			<MethodGoal>
				<VarGoalForm>
					<GoalName>review</GoalName>
					<ManyVarGoalArgument>
						<VarGoalArgument>
							<ParameterName>obj</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="is"/>
								<ComplexData>
									<t name="EXPC-OF"/>
									<ConceptName>technical paper</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
						<VarGoalArgument>
							<ParameterName>about</ParameterName>
							<MethodGoalArgument>
								<VariableName>?m</VariableName>
								<t name="is"/>
								<ComplexData>
									<t name="EXPC-OF"/>
									<ConceptName>knowledge adquisition</ConceptName>
								</ComplexData>
							</MethodGoalArgument>
						</VarGoalArgument>
					</ManyVarGoalArgument>
				</VarGoalForm>
			</MethodGoal>
		</capability>
	</capabilities>
</person>
